AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance with Auto Scaling Group for n8n deployment'

Parameters:
  Namespace:
    Type: String
    Description: Namespace/client identifier for isolated deployment
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: Must contain only lowercase letters, numbers, and hyphens
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the instance will be deployed
  
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for the EC2 instance
  
  InstanceType:
    Type: String
    Default: t4g.small
    AllowedValues:
      - t4g.small
      - t4g.medium
    Description: EC2 instance type (ARM-based for cost efficiency)
  
  InstanceProfileName:
    Type: String
    Description: Name of the IAM instance profile
    Default: ''
  
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for n8n files
    Default: ''

Conditions:
  HasInstanceProfile: !Not [!Equals [!Ref InstanceProfileName, '']]

Resources:
  N8nSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'n8n-${Namespace}-sg'
      GroupDescription: Security group for n8n instance - outbound only
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub 'n8n-${Namespace}-sg'
        - Key: Application
          Value: n8n
        - Key: Namespace
          Value: !Ref Namespace
        - Key: ManagedBy
          Value: CloudFormation

  N8nLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub 'n8n-${Namespace}-lt'
      LaunchTemplateData:
        ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          !If
            - HasInstanceProfile
            - Name: !Ref InstanceProfileName
            - !Ref 'AWS::NoValue'
        SecurityGroupIds:
          - !Ref N8nSecurityGroup
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 30
              VolumeType: gp3
              DeleteOnTermination: true
              Encrypted: true
        MetadataOptions:
          HttpTokens: required
          HttpPutResponseHopLimit: 1
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub 'n8n-${Namespace}-instance'
              - Key: Application
                Value: n8n
              - Key: ManagedBy
                Value: CloudFormation
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub 'n8n-${Namespace}-volume'
              - Key: Application
                Value: n8n
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            # Update system
            dnf update -y
            
            # Install Docker and PostgreSQL client tools
            dnf install -y docker git
            # Install PostgreSQL client - try 17 first, fallback to 16
            dnf install -y postgresql17 || dnf install -y postgresql16 || dnf install -y postgresql15
            
            # Start Docker
            systemctl start docker
            systemctl enable docker
            
            # Install Docker Compose plugin
            mkdir -p /usr/local/lib/docker/cli-plugins/
            curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-aarch64 -o /usr/local/lib/docker/cli-plugins/docker-compose
            chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            
            # Create n8n user
            useradd -m -s /bin/bash n8n
            usermod -aG docker n8n
            
            # Clone repository
            cd /home/n8n
            git clone https://github.com/cunicopia-dev/n8n-aws-self-hosting.git
            cd n8n-aws-self-hosting
            chown -R n8n:n8n /home/n8n/n8n-aws-self-hosting
            
            # Create directories with proper permissions for Docker
            mkdir -p n8n_data local-files
            chmod -R 777 n8n_data local-files
            
            # Create .env file with PostgreSQL
            cat > .env <<EOF
            N8N_ENCRYPTION_KEY=$(openssl rand -hex 24)
            GENERIC_TIMEZONE=UTC
            DB_TYPE=postgresdb
            DB_POSTGRESDB_DATABASE=n8n
            DB_POSTGRESDB_HOST=postgres
            DB_POSTGRESDB_PORT=5432
            DB_POSTGRESDB_USER=n8n
            DB_POSTGRESDB_PASSWORD=$(openssl rand -hex 16)
            S3_BUCKET=${S3BucketName}
            N8N_DIAGNOSTICS_ENABLED=false
            EOF
            
            # Start n8n with PostgreSQL
            docker compose --profile postgres up -d
            
            # Add ec2-user to docker group for SSM sessions
            usermod -aG docker ec2-user
            
            # Wait for containers to be healthy
            sleep 30
            
            # Setup backup scripts
            echo "Setting up automated backups..."
            mkdir -p /opt/n8n-scripts
            
            # Download backup scripts from S3
            aws s3 cp "s3://${S3BucketName}/scripts/backup-n8n.sh" /opt/n8n-scripts/ || echo "Backup script not found in S3"
            aws s3 cp "s3://${S3BucketName}/scripts/restore-n8n.sh" /opt/n8n-scripts/ || echo "Restore script not found in S3"
            aws s3 cp "s3://${S3BucketName}/scripts/backup-monitor.sh" /opt/n8n-scripts/ || echo "Monitor script not found in S3"
            aws s3 cp "s3://${S3BucketName}/scripts/backup-utils.sh" /opt/n8n-scripts/ || echo "Utils script not found in S3"
            
            # Set permissions and environment
            chmod +x /opt/n8n-scripts/*.sh 2>/dev/null || true
            echo "export NAMESPACE=${Namespace}" >> /etc/environment
            echo "export S3_BUCKET=${S3BucketName}" >> /etc/environment
            
            # Create convenient symlinks
            ln -sf /opt/n8n-scripts/backup-utils.sh /usr/local/bin/n8n-backup 2>/dev/null || true
            ln -sf /opt/n8n-scripts/restore-n8n.sh /usr/local/bin/n8n-restore 2>/dev/null || true
            
            # Create backup log directory
            mkdir -p /var/log
            touch /var/log/n8n-backup.log /var/log/n8n-restore.log /var/log/n8n-backup-monitor.log
            chown n8n:n8n /var/log/n8n-*.log
            
            # Setup cron jobs for n8n user
            cat > /tmp/n8n-cron <<EOF
            # Environment variables
            NAMESPACE=${Namespace}
            S3_BUCKET=${S3BucketName}
            PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            
            # Daily backup at 2 AM
            0 2 * * * /opt/n8n-scripts/backup-n8n.sh >> /var/log/n8n-backup.log 2>&1
            
            # Backup health check every 6 hours
            0 */6 * * * /opt/n8n-scripts/backup-monitor.sh >> /var/log/n8n-backup-monitor.log 2>&1
            EOF
            
            # Install cron for n8n user
            crontab -u n8n /tmp/n8n-cron
            rm /tmp/n8n-cron
            
            # Enable cron service
            systemctl enable crond
            systemctl start crond
            
            # Setup CloudWatch logs
            dnf install -y amazon-cloudwatch-agent
            cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<EOF
            {
              "logs": {
                "logs_collected": {
                  "files": {
                    "collect_list": [
                      {
                        "file_path": "/var/log/messages",
                        "log_group_name": "/aws/ec2/n8n/system",
                        "log_stream_name": "{instance_id}/messages"
                      }
                    ]
                  }
                }
              }
            }
            EOF
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

  N8nAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub 'n8n-${Namespace}-asg'
      VPCZoneIdentifier:
        - !Ref SubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref N8nLaunchTemplate
        Version: !GetAtt N8nLaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub 'n8n-${Namespace}-asg-instance'
          PropagateAtLaunch: true
        - Key: Application
          Value: n8n
        - Key: Namespace
          Value: !Ref Namespace
          PropagateAtLaunch: true
        - Key: ManagedBy
          Value: CloudFormation
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group
    Value: !Ref N8nAutoScalingGroup
    Export:
      Name: !Sub '${AWS::StackName}-ASGName'
  
  SecurityGroupId:
    Description: ID of the security group
    Value: !Ref N8nSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'
  
  LaunchTemplateId:
    Description: ID of the launch template
    Value: !Ref N8nLaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-LaunchTemplateId'
  
  InstanceId:
    Description: Instance ID (retrieve using ASG describe-instances)
    Value: !Sub 'Use "aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names ${N8nAutoScalingGroup}" to get instance ID'