AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for n8n file storage'

Parameters:
  Namespace:
    Type: String
    Description: Namespace/client identifier for isolated deployment
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: Must contain only lowercase letters, numbers, and hyphens
  
  BucketPrefix:
    Type: String
    Default: n8n-files
    Description: Prefix for the S3 bucket name (will append namespace, account ID and region)

Resources:
  N8nFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketPrefix}-${Namespace}-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      Tags:
        - Key: Application
          Value: n8n
        - Key: Namespace
          Value: !Ref Namespace
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref N8nFilesBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt N8nFilesBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'